server:
  port: 9093
spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/learneasy
  kafka:
    bootstrap-servers: localhost:9092
    schema-registry-url: http://localhost:8081
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: io.confluent.kafka.serializers.KafkaAvroSerializer
      retries: 0
      batch-size: 16384
      buffer-memory: 33554432
    consumer:
      bootstrap-servers: localhost:9092
      group-id: bid-group-id4
      auto-offset-reset: earliest
      properties:
        schema.registry.url: http://localhost:8081
        specific.avro.reader: true
      value-deserializer: io.confluent.kafka.serializers.KafkaAvroDeserializer
        #spring:
#  datasource:
#    url: jdbc:h2:mem:mydb
#    username: sa
#    password: password
#    driverClassName: org.h2.Driver
#  jpa:
#    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
#docker run -d -p "27017:27017" mongo