/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.avro.le;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class Schedule extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -66886357991969538L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"Schedule\",\"namespace\":\"com.avro.le\",\"fields\":[{\"name\":\"startDateTime\",\"type\":\"string\"},{\"name\":\"endDateTime\",\"type\":\"string\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<Schedule> ENCODER =
      new BinaryMessageEncoder<Schedule>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<Schedule> DECODER =
      new BinaryMessageDecoder<Schedule>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<Schedule> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<Schedule> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<Schedule> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<Schedule>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this Schedule to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a Schedule from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a Schedule instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static Schedule fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

   private java.lang.CharSequence startDateTime;
   private java.lang.CharSequence endDateTime;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public Schedule() {}

  /**
   * All-args constructor.
   * @param startDateTime The new value for startDateTime
   * @param endDateTime The new value for endDateTime
   */
  public Schedule(java.lang.CharSequence startDateTime, java.lang.CharSequence endDateTime) {
    this.startDateTime = startDateTime;
    this.endDateTime = endDateTime;
  }

  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return startDateTime;
    case 1: return endDateTime;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: startDateTime = (java.lang.CharSequence)value$; break;
    case 1: endDateTime = (java.lang.CharSequence)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'startDateTime' field.
   * @return The value of the 'startDateTime' field.
   */
  public java.lang.CharSequence getStartDateTime() {
    return startDateTime;
  }


  /**
   * Sets the value of the 'startDateTime' field.
   * @param value the value to set.
   */
  public void setStartDateTime(java.lang.CharSequence value) {
    this.startDateTime = value;
  }

  /**
   * Gets the value of the 'endDateTime' field.
   * @return The value of the 'endDateTime' field.
   */
  public java.lang.CharSequence getEndDateTime() {
    return endDateTime;
  }


  /**
   * Sets the value of the 'endDateTime' field.
   * @param value the value to set.
   */
  public void setEndDateTime(java.lang.CharSequence value) {
    this.endDateTime = value;
  }

  /**
   * Creates a new Schedule RecordBuilder.
   * @return A new Schedule RecordBuilder
   */
  public static com.avro.le.Schedule.Builder newBuilder() {
    return new com.avro.le.Schedule.Builder();
  }

  /**
   * Creates a new Schedule RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new Schedule RecordBuilder
   */
  public static com.avro.le.Schedule.Builder newBuilder(com.avro.le.Schedule.Builder other) {
    if (other == null) {
      return new com.avro.le.Schedule.Builder();
    } else {
      return new com.avro.le.Schedule.Builder(other);
    }
  }

  /**
   * Creates a new Schedule RecordBuilder by copying an existing Schedule instance.
   * @param other The existing instance to copy.
   * @return A new Schedule RecordBuilder
   */
  public static com.avro.le.Schedule.Builder newBuilder(com.avro.le.Schedule other) {
    if (other == null) {
      return new com.avro.le.Schedule.Builder();
    } else {
      return new com.avro.le.Schedule.Builder(other);
    }
  }

  /**
   * RecordBuilder for Schedule instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<Schedule>
    implements org.apache.avro.data.RecordBuilder<Schedule> {

    private java.lang.CharSequence startDateTime;
    private java.lang.CharSequence endDateTime;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.avro.le.Schedule.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.startDateTime)) {
        this.startDateTime = data().deepCopy(fields()[0].schema(), other.startDateTime);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.endDateTime)) {
        this.endDateTime = data().deepCopy(fields()[1].schema(), other.endDateTime);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
    }

    /**
     * Creates a Builder by copying an existing Schedule instance
     * @param other The existing instance to copy.
     */
    private Builder(com.avro.le.Schedule other) {
      super(SCHEMA$);
      if (isValidValue(fields()[0], other.startDateTime)) {
        this.startDateTime = data().deepCopy(fields()[0].schema(), other.startDateTime);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.endDateTime)) {
        this.endDateTime = data().deepCopy(fields()[1].schema(), other.endDateTime);
        fieldSetFlags()[1] = true;
      }
    }

    /**
      * Gets the value of the 'startDateTime' field.
      * @return The value.
      */
    public java.lang.CharSequence getStartDateTime() {
      return startDateTime;
    }


    /**
      * Sets the value of the 'startDateTime' field.
      * @param value The value of 'startDateTime'.
      * @return This builder.
      */
    public com.avro.le.Schedule.Builder setStartDateTime(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.startDateTime = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'startDateTime' field has been set.
      * @return True if the 'startDateTime' field has been set, false otherwise.
      */
    public boolean hasStartDateTime() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'startDateTime' field.
      * @return This builder.
      */
    public com.avro.le.Schedule.Builder clearStartDateTime() {
      startDateTime = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'endDateTime' field.
      * @return The value.
      */
    public java.lang.CharSequence getEndDateTime() {
      return endDateTime;
    }


    /**
      * Sets the value of the 'endDateTime' field.
      * @param value The value of 'endDateTime'.
      * @return This builder.
      */
    public com.avro.le.Schedule.Builder setEndDateTime(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.endDateTime = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'endDateTime' field has been set.
      * @return True if the 'endDateTime' field has been set, false otherwise.
      */
    public boolean hasEndDateTime() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'endDateTime' field.
      * @return This builder.
      */
    public com.avro.le.Schedule.Builder clearEndDateTime() {
      endDateTime = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public Schedule build() {
      try {
        Schedule record = new Schedule();
        record.startDateTime = fieldSetFlags()[0] ? this.startDateTime : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.endDateTime = fieldSetFlags()[1] ? this.endDateTime : (java.lang.CharSequence) defaultValue(fields()[1]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<Schedule>
    WRITER$ = (org.apache.avro.io.DatumWriter<Schedule>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<Schedule>
    READER$ = (org.apache.avro.io.DatumReader<Schedule>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeString(this.startDateTime);

    out.writeString(this.endDateTime);

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.startDateTime = in.readString(this.startDateTime instanceof Utf8 ? (Utf8)this.startDateTime : null);

      this.endDateTime = in.readString(this.endDateTime instanceof Utf8 ? (Utf8)this.endDateTime : null);

    } else {
      for (int i = 0; i < 2; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.startDateTime = in.readString(this.startDateTime instanceof Utf8 ? (Utf8)this.startDateTime : null);
          break;

        case 1:
          this.endDateTime = in.readString(this.endDateTime instanceof Utf8 ? (Utf8)this.endDateTime : null);
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










